#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xf51a0302, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x489a2089, __VMLINUX_SYMBOL_STR(drm_release) },
	{ 0xb1485c34, __VMLINUX_SYMBOL_STR(drm_prime_gem_destroy) },
	{ 0xc045fc79, __VMLINUX_SYMBOL_STR(drm_fb_helper_set_par) },
	{ 0xb8b5974, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x32774149, __VMLINUX_SYMBOL_STR(drm_crtc_helper_set_config) },
	{ 0x1ca8d45c, __VMLINUX_SYMBOL_STR(drm_dev_register) },
	{ 0xdca08e40, __VMLINUX_SYMBOL_STR(drm_connector_unplug_all) },
	{ 0xa8e19555, __VMLINUX_SYMBOL_STR(drm_gem_put_pages) },
	{ 0xa30ae3a9, __VMLINUX_SYMBOL_STR(drm_dev_alloc) },
	{ 0xc2259708, __VMLINUX_SYMBOL_STR(drm_fb_helper_initial_config) },
	{ 0x7aa1756e, __VMLINUX_SYMBOL_STR(kvfree) },
	{ 0x1494ad7b, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x9601d244, __VMLINUX_SYMBOL_STR(drm_gem_dmabuf_release) },
	{ 0xa6e6d8ef, __VMLINUX_SYMBOL_STR(drm_mode_config_cleanup) },
	{ 0xb886cffb, __VMLINUX_SYMBOL_STR(drm_unplug_dev) },
	{ 0x1c792a04, __VMLINUX_SYMBOL_STR(arm_dma_ops) },
	{ 0xde3fcb1b, __VMLINUX_SYMBOL_STR(drm_fb_helper_unlink_fbi) },
	{ 0x1394225, __VMLINUX_SYMBOL_STR(dma_buf_detach) },
	{ 0x5cb074b1, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_leave) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x1afae5e7, __VMLINUX_SYMBOL_STR(down_interruptible) },
	{ 0xe9fdf1b3, __VMLINUX_SYMBOL_STR(drm_helper_probe_single_connector_modes) },
	{ 0xd5152710, __VMLINUX_SYMBOL_STR(sg_next) },
	{ 0x32053440, __VMLINUX_SYMBOL_STR(drm_gem_free_mmap_offset) },
	{ 0xa29287e8, __VMLINUX_SYMBOL_STR(drm_vblank_cleanup) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0x9580deb, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x85d23016, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x5500c89, __VMLINUX_SYMBOL_STR(drm_dev_unref) },
	{ 0x816366e1, __VMLINUX_SYMBOL_STR(drm_vblank_init) },
	{ 0x9b5bd860, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0xf76b0a59, __VMLINUX_SYMBOL_STR(read_current_timer) },
	{ 0x42df7f10, __VMLINUX_SYMBOL_STR(drm_connector_cleanup) },
	{ 0x1c142e2b, __VMLINUX_SYMBOL_STR(drm_fb_helper_unregister_fbi) },
	{ 0x6d6104cd, __VMLINUX_SYMBOL_STR(dma_buf_vunmap) },
	{ 0x35365cf4, __VMLINUX_SYMBOL_STR(usb_get_descriptor) },
	{ 0x804b9718, __VMLINUX_SYMBOL_STR(drm_fb_helper_pan_display) },
	{ 0xe707d823, __VMLINUX_SYMBOL_STR(__aeabi_uidiv) },
	{ 0xb0136c86, __VMLINUX_SYMBOL_STR(drm_helper_connector_dpms) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x57ecc0c4, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0x3744cf36, __VMLINUX_SYMBOL_STR(vmalloc_to_pfn) },
	{ 0x51d559d1, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xf232f1e, __VMLINUX_SYMBOL_STR(drm_prime_pages_to_sg) },
	{ 0xa4bc8397, __VMLINUX_SYMBOL_STR(usb_deregister) },
	{ 0xdefcbe, __VMLINUX_SYMBOL_STR(drm_helper_mode_fill_fb_struct) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x6aeacc72, __VMLINUX_SYMBOL_STR(drm_object_attach_property) },
	{ 0xfc082392, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0x1f94d0b4, __VMLINUX_SYMBOL_STR(drm_gem_dumb_destroy) },
	{ 0x961c6592, __VMLINUX_SYMBOL_STR(vmap) },
	{ 0xb0a202ae, __VMLINUX_SYMBOL_STR(dma_buf_put) },
	{ 0x480047a9, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_var) },
	{ 0xfacd2e14, __VMLINUX_SYMBOL_STR(pgprot_user) },
	{ 0x65e07d0b, __VMLINUX_SYMBOL_STR(usb_control_msg) },
	{ 0x95ccb933, __VMLINUX_SYMBOL_STR(drm_send_vblank_event) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x3934a77b, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xd0a783fa, __VMLINUX_SYMBOL_STR(drm_gem_object_release) },
	{ 0x30574af0, __VMLINUX_SYMBOL_STR(drm_read) },
	{ 0xf6944d79, __VMLINUX_SYMBOL_STR(noop_llseek) },
	{ 0x49d87b7f, __VMLINUX_SYMBOL_STR(drm_add_edid_modes) },
	{ 0x1106bf18, __VMLINUX_SYMBOL_STR(drm_fb_helper_release_fbi) },
	{ 0x8cdb8696, __VMLINUX_SYMBOL_STR(dma_buf_unmap_attachment) },
	{ 0x891035f7, __VMLINUX_SYMBOL_STR(usb_free_coherent) },
	{ 0x1dd71f7a, __VMLINUX_SYMBOL_STR(drm_err) },
	{ 0xce74ac74, __VMLINUX_SYMBOL_STR(drm_connector_init) },
	{ 0x2196324, __VMLINUX_SYMBOL_STR(__aeabi_idiv) },
	{ 0x9878846a, __VMLINUX_SYMBOL_STR(drm_fb_helper_prepare) },
	{ 0xadd5783, __VMLINUX_SYMBOL_STR(drm_gem_vm_open) },
	{ 0x6cfdda1, __VMLINUX_SYMBOL_STR(drm_mode_connector_update_edid_property) },
	{ 0x63726898, __VMLINUX_SYMBOL_STR(vm_insert_page) },
	{ 0x1bdea3e7, __VMLINUX_SYMBOL_STR(drm_gem_vm_close) },
	{ 0x20645642, __VMLINUX_SYMBOL_STR(drm_debug) },
	{ 0x4ea1f5a2, __VMLINUX_SYMBOL_STR(drm_gem_object_free) },
	{ 0xcdd158d, __VMLINUX_SYMBOL_STR(sg_alloc_table) },
	{ 0xe3d0b10c, __VMLINUX_SYMBOL_STR(drm_gem_prime_fd_to_handle) },
	{ 0x3991d651, __VMLINUX_SYMBOL_STR(dma_buf_begin_cpu_access) },
	{ 0x729a7350, __VMLINUX_SYMBOL_STR(drm_ioctl) },
	{ 0xfbeb2802, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_imageblit) },
	{ 0x15597bd3, __VMLINUX_SYMBOL_STR(usb_submit_urb) },
	{ 0x25098fea, __VMLINUX_SYMBOL_STR(drm_gem_mmap) },
	{ 0xbf51838b, __VMLINUX_SYMBOL_STR(dma_buf_map_attachment) },
	{ 0x2a4bbd17, __VMLINUX_SYMBOL_STR(dma_buf_export) },
	{ 0x3e2b3594, __VMLINUX_SYMBOL_STR(drm_framebuffer_unregister_private) },
	{ 0xa3291d10, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0x5024b7ac, __VMLINUX_SYMBOL_STR(drm_fb_helper_check_var) },
	{ 0x270d3fd0, __VMLINUX_SYMBOL_STR(drm_fb_helper_blank) },
	{ 0xb24849fe, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0xfd1fdf8e, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x84024ae5, __VMLINUX_SYMBOL_STR(drm_fb_helper_alloc_fbi) },
	{ 0x18ca93a6, __VMLINUX_SYMBOL_STR(drm_crtc_init) },
	{ 0x598542b2, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x5bb21880, __VMLINUX_SYMBOL_STR(dma_buf_attach) },
	{ 0xd0678c89, __VMLINUX_SYMBOL_STR(drm_gem_prime_handle_to_fd) },
	{ 0xb292b498, __VMLINUX_SYMBOL_STR(get_device) },
	{ 0x5b8b7228, __VMLINUX_SYMBOL_STR(drm_connector_unregister) },
	{ 0x99c0c730, __VMLINUX_SYMBOL_STR(drm_gem_object_init) },
	{ 0x47f138e6, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0x3b0cc79b, __VMLINUX_SYMBOL_STR(fb_deferred_io_cleanup) },
	{ 0x1c9239f2, __VMLINUX_SYMBOL_STR(fb_deferred_io_init) },
	{ 0x20146b7, __VMLINUX_SYMBOL_STR(drm_gem_create_mmap_offset) },
	{ 0xa5fe57a7, __VMLINUX_SYMBOL_STR(drm_mode_create_dirty_info_property) },
	{ 0x62d7cbb1, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0x28d6861d, __VMLINUX_SYMBOL_STR(__vmalloc) },
	{ 0x62f92f03, __VMLINUX_SYMBOL_STR(drm_mode_config_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x94961283, __VMLINUX_SYMBOL_STR(vunmap) },
	{ 0x3a53f36b, __VMLINUX_SYMBOL_STR(remap_pfn_range) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x4be7fb63, __VMLINUX_SYMBOL_STR(up) },
	{ 0x58963f53, __VMLINUX_SYMBOL_STR(usb_register_driver) },
	{ 0x1db7dc40, __VMLINUX_SYMBOL_STR(pgprot_kernel) },
	{ 0xa7fc51c, __VMLINUX_SYMBOL_STR(drm_fb_helper_fini) },
	{ 0x986481bb, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all) },
	{ 0x9cd60539, __VMLINUX_SYMBOL_STR(sg_free_table) },
	{ 0x3e884f4b, __VMLINUX_SYMBOL_STR(vm_get_page_prot) },
	{ 0xf46842aa, __VMLINUX_SYMBOL_STR(drm_prime_sg_to_page_addr_arrays) },
	{ 0x2f4acc53, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_fillrect) },
	{ 0xae4fd01b, __VMLINUX_SYMBOL_STR(drm_modeset_unlock_all) },
	{ 0x61dc20f5, __VMLINUX_SYMBOL_STR(drm_helper_disable_unused_functions) },
	{ 0x3858e4e4, __VMLINUX_SYMBOL_STR(dma_buf_end_cpu_access) },
	{ 0x912a00da, __VMLINUX_SYMBOL_STR(drm_fb_helper_setcmap) },
	{ 0xfb6f5fba, __VMLINUX_SYMBOL_STR(usb_alloc_coherent) },
	{ 0x16265d1b, __VMLINUX_SYMBOL_STR(drm_framebuffer_init) },
	{ 0xc360e7e2, __VMLINUX_SYMBOL_STR(drm_ut_debug_printk) },
	{ 0x8593719e, __VMLINUX_SYMBOL_STR(dma_buf_vmap) },
	{ 0x54b0aabb, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_copyarea) },
	{ 0xda95a00c, __VMLINUX_SYMBOL_STR(drm_gem_get_pages) },
	{ 0x8f4e9b6a, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_fix) },
	{ 0x50cc9353, __VMLINUX_SYMBOL_STR(drm_connector_register) },
	{ 0x3ac1fef9, __VMLINUX_SYMBOL_STR(drm_mode_legacy_fb_format) },
	{ 0x33e12395, __VMLINUX_SYMBOL_STR(usb_free_urb) },
	{ 0x837d0f0a, __VMLINUX_SYMBOL_STR(down_timeout) },
	{ 0xc7ffba43, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_disable) },
	{ 0x892f343b, __VMLINUX_SYMBOL_STR(drm_mode_object_find) },
	{ 0xbf3e54ea, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_enter) },
	{ 0x82e4efca, __VMLINUX_SYMBOL_STR(drm_poll) },
	{ 0xc309f1ee, __VMLINUX_SYMBOL_STR(drm_fb_helper_init) },
	{ 0x1ebc1af, __VMLINUX_SYMBOL_STR(drm_fb_helper_single_add_all_connectors) },
	{ 0x9909033d, __VMLINUX_SYMBOL_STR(usb_alloc_urb) },
	{ 0xa0ffc40e, __VMLINUX_SYMBOL_STR(drm_open) },
	{ 0xfce9d8c6, __VMLINUX_SYMBOL_STR(drm_framebuffer_cleanup) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=drm,drm_kms_helper";

MODULE_ALIAS("usb:v17E9p*d*dc*dsc*dp*icFFisc00ip00in*");

MODULE_INFO(srcversion, "ABC4023F73116DB27CE21DF");
