#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xf51a0302, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x92b57248, __VMLINUX_SYMBOL_STR(flush_work) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0xa6f49c9b, __VMLINUX_SYMBOL_STR(drm_atomic_get_connector_state) },
	{ 0xb8b5974, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xf902af15, __VMLINUX_SYMBOL_STR(drm_atomic_legacy_backoff) },
	{ 0xfd60df2, __VMLINUX_SYMBOL_STR(drm_get_connector_status_name) },
	{ 0x7b86dbe6, __VMLINUX_SYMBOL_STR(drm_calc_timestamping_constants) },
	{ 0x3f4eb73c, __VMLINUX_SYMBOL_STR(drm_get_edid) },
	{ 0xc6717328, __VMLINUX_SYMBOL_STR(drm_crtc_index) },
	{ 0x91fec1cc, __VMLINUX_SYMBOL_STR(drm_rect_calc_vscale) },
	{ 0x349cba85, __VMLINUX_SYMBOL_STR(strchr) },
	{ 0x3b92c1d, __VMLINUX_SYMBOL_STR(drm_framebuffer_reference) },
	{ 0x1494ad7b, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x1e274816, __VMLINUX_SYMBOL_STR(drm_bridge_disable) },
	{ 0x7eaa817, __VMLINUX_SYMBOL_STR(drm_edid_to_eld) },
	{ 0xf706fa32, __VMLINUX_SYMBOL_STR(drm_mode_create_from_cmdline_mode) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x70d9e5a8, __VMLINUX_SYMBOL_STR(framebuffer_release) },
	{ 0xd10becd0, __VMLINUX_SYMBOL_STR(drm_gem_cma_create) },
	{ 0x8de13715, __VMLINUX_SYMBOL_STR(drm_format_vert_chroma_subsampling) },
	{ 0x635d246, __VMLINUX_SYMBOL_STR(drm_bridge_pre_enable) },
	{ 0xeedcc19a, __VMLINUX_SYMBOL_STR(unlink_framebuffer) },
	{ 0x39bd447f, __VMLINUX_SYMBOL_STR(drm_atomic_state_clear) },
	{ 0xd3dbfbc4, __VMLINUX_SYMBOL_STR(_find_first_zero_bit_le) },
	{ 0xdd879e08, __VMLINUX_SYMBOL_STR(drm_mode_destroy) },
	{ 0x4d974b9c, __VMLINUX_SYMBOL_STR(register_sysrq_key) },
	{ 0xaedc4f0, __VMLINUX_SYMBOL_STR(drm_atomic_connectors_for_crtc) },
	{ 0x970052a0, __VMLINUX_SYMBOL_STR(drm_atomic_get_plane_state) },
	{ 0x17a8ac7a, __VMLINUX_SYMBOL_STR(fb_sys_read) },
	{ 0xf1421d13, __VMLINUX_SYMBOL_STR(drm_mode_sort) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0xd1e79cae, __VMLINUX_SYMBOL_STR(fence_wait_timeout) },
	{ 0x32653dd7, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0xe2fae716, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0x50a582f6, __VMLINUX_SYMBOL_STR(cfb_fillrect) },
	{ 0xad7ce9b0, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x9580deb, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x4c29dcbf, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0x85d23016, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x85df9b6c, __VMLINUX_SYMBOL_STR(strsep) },
	{ 0xe0196374, __VMLINUX_SYMBOL_STR(drm_plane_force_disable) },
	{ 0xca45efbc, __VMLINUX_SYMBOL_STR(drm_format_horz_chroma_subsampling) },
	{ 0x183357e7, __VMLINUX_SYMBOL_STR(platform_device_register_full) },
	{ 0x99d37efc, __VMLINUX_SYMBOL_STR(drm_object_property_set_value) },
	{ 0x42246c4, __VMLINUX_SYMBOL_STR(sys_copyarea) },
	{ 0xd2873974, __VMLINUX_SYMBOL_STR(drm_mode_validate_basic) },
	{ 0x37e74642, __VMLINUX_SYMBOL_STR(get_jiffies_64) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0xb6656584, __VMLINUX_SYMBOL_STR(drm_universal_plane_init) },
	{ 0xc21dd035, __VMLINUX_SYMBOL_STR(drm_atomic_set_mode_prop_for_crtc) },
	{ 0x68fbf2d0, __VMLINUX_SYMBOL_STR(i2c_add_adapter) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0x131db64a, __VMLINUX_SYMBOL_STR(system_long_wq) },
	{ 0x100af0a6, __VMLINUX_SYMBOL_STR(param_ops_string) },
	{ 0x621cbb4c, __VMLINUX_SYMBOL_STR(drm_atomic_set_mode_for_crtc) },
	{ 0xa6d7eff, __VMLINUX_SYMBOL_STR(fb_set_suspend) },
	{ 0x275ef902, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xd2335101, __VMLINUX_SYMBOL_STR(drm_fb_get_bpp_depth) },
	{ 0xe707d823, __VMLINUX_SYMBOL_STR(__aeabi_uidiv) },
	{ 0x59ef50f0, __VMLINUX_SYMBOL_STR(drm_edid_block_valid) },
	{ 0xdd0a2ba2, __VMLINUX_SYMBOL_STR(strlcat) },
	{ 0x88ab6fe3, __VMLINUX_SYMBOL_STR(kgdb_active) },
	{ 0xe385c06c, __VMLINUX_SYMBOL_STR(drm_bridge_post_disable) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0xc9fbd99d, __VMLINUX_SYMBOL_STR(drm_atomic_crtc_set_property) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xe436e56a, __VMLINUX_SYMBOL_STR(drm_atomic_state_alloc) },
	{ 0x170259b4, __VMLINUX_SYMBOL_STR(drm_mode_copy) },
	{ 0x2c900393, __VMLINUX_SYMBOL_STR(drm_atomic_commit) },
	{ 0xde82b270, __VMLINUX_SYMBOL_STR(drm_mode_find_dmt) },
	{ 0x59c5ec88, __VMLINUX_SYMBOL_STR(drm_plane_index) },
	{ 0xe7cbac0e, __VMLINUX_SYMBOL_STR(cfb_imageblit) },
	{ 0xbd7da979, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x4d50c1e2, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_put) },
	{ 0x7f4916, __VMLINUX_SYMBOL_STR(drm_bridge_enable) },
	{ 0x45f768a8, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xcde6159a, __VMLINUX_SYMBOL_STR(drm_mode_duplicate) },
	{ 0x7a890c8, __VMLINUX_SYMBOL_STR(fb_alloc_cmap) },
	{ 0x240ab166, __VMLINUX_SYMBOL_STR(drm_crtc_init_with_planes) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xdf8a365a, __VMLINUX_SYMBOL_STR(drm_atomic_set_crtc_for_connector) },
	{ 0xfc082392, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0x447f9d6d, __VMLINUX_SYMBOL_STR(drm_atomic_state_free) },
	{ 0x9fb9fb50, __VMLINUX_SYMBOL_STR(drm_atomic_plane_set_property) },
	{ 0x8931d6cc, __VMLINUX_SYMBOL_STR(drm_property_unreference_blob) },
	{ 0x5b10feb5, __VMLINUX_SYMBOL_STR(register_framebuffer) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x84b183ae, __VMLINUX_SYMBOL_STR(strncmp) },
	{ 0x73e20c1c, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x3934a77b, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x3ecfd409, __VMLINUX_SYMBOL_STR(drm_framebuffer_unreference) },
	{ 0x3c473d74, __VMLINUX_SYMBOL_STR(drm_modeset_legacy_acquire_ctx) },
	{ 0x49d87b7f, __VMLINUX_SYMBOL_STR(drm_add_edid_modes) },
	{ 0x3a249a9e, __VMLINUX_SYMBOL_STR(platform_device_unregister) },
	{ 0x8e865d3c, __VMLINUX_SYMBOL_STR(arm_delay_ops) },
	{ 0xcb9dbc91, __VMLINUX_SYMBOL_STR(drm_atomic_set_fb_for_plane) },
	{ 0x1dd71f7a, __VMLINUX_SYMBOL_STR(drm_err) },
	{ 0x2196324, __VMLINUX_SYMBOL_STR(__aeabi_idiv) },
	{ 0x6cfdda1, __VMLINUX_SYMBOL_STR(drm_mode_connector_update_edid_property) },
	{ 0x15f50327, __VMLINUX_SYMBOL_STR(drm_modeset_lock) },
	{ 0x20645642, __VMLINUX_SYMBOL_STR(drm_debug) },
	{ 0x8357967a, __VMLINUX_SYMBOL_STR(drm_mode_validate_size) },
	{ 0xfbfefd6f, __VMLINUX_SYMBOL_STR(drm_crtc_wait_one_vblank) },
	{ 0x62d436bd, __VMLINUX_SYMBOL_STR(drm_crtc_get_hv_timing) },
	{ 0x4ea1f5a2, __VMLINUX_SYMBOL_STR(drm_gem_object_free) },
	{ 0xdcd5bd9d, __VMLINUX_SYMBOL_STR(drm_mode_connector_list_update) },
	{ 0x82c6094, __VMLINUX_SYMBOL_STR(drm_atomic_get_crtc_state) },
	{ 0x98b71c6, __VMLINUX_SYMBOL_STR(fb_dealloc_cmap) },
	{ 0x4059792f, __VMLINUX_SYMBOL_STR(print_hex_dump) },
	{ 0xd0dd2559, __VMLINUX_SYMBOL_STR(i2c_del_adapter) },
	{ 0xf837b64a, __VMLINUX_SYMBOL_STR(drm_mode_set_crtcinfo) },
	{ 0x23f58fa1, __VMLINUX_SYMBOL_STR(drm_plane_cleanup) },
	{ 0xb1c3a01a, __VMLINUX_SYMBOL_STR(oops_in_progress) },
	{ 0x27683889, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0x81096fe4, __VMLINUX_SYMBOL_STR(drm_mode_prune_invalid) },
	{ 0x97a380b0, __VMLINUX_SYMBOL_STR(drm_atomic_set_crtc_for_plane) },
	{ 0x12a38747, __VMLINUX_SYMBOL_STR(usleep_range) },
	{ 0x46c2ec70, __VMLINUX_SYMBOL_STR(sys_fillrect) },
	{ 0x3e2b3594, __VMLINUX_SYMBOL_STR(drm_framebuffer_unregister_private) },
	{ 0x3f616ce2, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0x59aa14cf, __VMLINUX_SYMBOL_STR(fence_release) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x9dd752c1, __VMLINUX_SYMBOL_STR(sys_imageblit) },
	{ 0x7772178e, __VMLINUX_SYMBOL_STR(drm_sysfs_hotplug_event) },
	{ 0x38a4f7ae, __VMLINUX_SYMBOL_STR(drm_format_num_planes) },
	{ 0x1122d1cd, __VMLINUX_SYMBOL_STR(fb_sys_write) },
	{ 0x8ccd70de, __VMLINUX_SYMBOL_STR(drm_mode_debug_printmodeline) },
	{ 0x2c652695, __VMLINUX_SYMBOL_STR(drm_bridge_mode_fixup) },
	{ 0xb24849fe, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0x7de0183e, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_get) },
	{ 0x2ebad65b, __VMLINUX_SYMBOL_STR(drm_add_modes_noedid) },
	{ 0x3b9d009a, __VMLINUX_SYMBOL_STR(drm_format_plane_cpp) },
	{ 0x4a8ccf1, __VMLINUX_SYMBOL_STR(drm_atomic_connector_set_property) },
	{ 0xfd1fdf8e, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xacb1ea89, __VMLINUX_SYMBOL_STR(drm_warn_on_modeset_not_all_locked) },
	{ 0xa308a95d, __VMLINUX_SYMBOL_STR(drm_atomic_clean_old_fb) },
	{ 0x3d97af84, __VMLINUX_SYMBOL_STR(drm_gem_cma_describe) },
	{ 0xd85cd67e, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0xd8a4ac6c, __VMLINUX_SYMBOL_STR(framebuffer_alloc) },
	{ 0x344b7739, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x3cd1b6e0, __VMLINUX_SYMBOL_STR(drm_mode_set_config_internal) },
	{ 0xa28078b2, __VMLINUX_SYMBOL_STR(drm_edid_duplicate) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x6900d335, __VMLINUX_SYMBOL_STR(drm_rect_clip_scaled) },
	{ 0x2256fafa, __VMLINUX_SYMBOL_STR(div64_u64_rem) },
	{ 0xf2318908, __VMLINUX_SYMBOL_STR(drm_mode_equal) },
	{ 0x92e3cae0, __VMLINUX_SYMBOL_STR(request_firmware) },
	{ 0x986481bb, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all) },
	{ 0x1cfb04fa, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0xd2adb12f, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_count) },
	{ 0x2d50570f, __VMLINUX_SYMBOL_STR(drm_rect_calc_hscale) },
	{ 0x12452842, __VMLINUX_SYMBOL_STR(cfb_copyarea) },
	{ 0xf85d0178, __VMLINUX_SYMBOL_STR(drm_atomic_add_affected_connectors) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0x8083c7ed, __VMLINUX_SYMBOL_STR(drm_mode_probed_add) },
	{ 0xb2d48a2e, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xae4fd01b, __VMLINUX_SYMBOL_STR(drm_modeset_unlock_all) },
	{ 0x2830e491, __VMLINUX_SYMBOL_STR(drm_bridge_mode_set) },
	{ 0xaa895396, __VMLINUX_SYMBOL_STR(drm_mode_plane_set_obj_prop) },
	{ 0xab81cb61, __VMLINUX_SYMBOL_STR(drm_atomic_add_affected_planes) },
	{ 0x16265d1b, __VMLINUX_SYMBOL_STR(drm_framebuffer_init) },
	{ 0x65eb3e0e, __VMLINUX_SYMBOL_STR(drm_mode_connector_set_tile_property) },
	{ 0xc360e7e2, __VMLINUX_SYMBOL_STR(drm_ut_debug_printk) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0xcbc9557f, __VMLINUX_SYMBOL_STR(unregister_sysrq_key) },
	{ 0x3ac1fef9, __VMLINUX_SYMBOL_STR(drm_mode_legacy_fb_format) },
	{ 0x22f9223c, __VMLINUX_SYMBOL_STR(release_firmware) },
	{ 0xb859f38b, __VMLINUX_SYMBOL_STR(krealloc) },
	{ 0xd9603285, __VMLINUX_SYMBOL_STR(drm_mode_vrefresh) },
	{ 0x96d26911, __VMLINUX_SYMBOL_STR(drm_property_reference_blob) },
	{ 0xd827d286, __VMLINUX_SYMBOL_STR(drm_atomic_async_commit) },
	{ 0xfce9d8c6, __VMLINUX_SYMBOL_STR(drm_framebuffer_cleanup) },
	{ 0x6a74c672, __VMLINUX_SYMBOL_STR(unregister_framebuffer) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=drm,fb_sys_fops,syscopyarea,sysfillrect,sysimgblt";


MODULE_INFO(srcversion, "7979999D268BF6CF9C3D15D");
