#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xf51a0302, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xb077e70a, __VMLINUX_SYMBOL_STR(clk_unprepare) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0xa6c4ad07, __VMLINUX_SYMBOL_STR(drm_gem_prime_export) },
	{ 0xce102fc0, __VMLINUX_SYMBOL_STR(rpi_firmware_transaction) },
	{ 0x75341a14, __VMLINUX_SYMBOL_STR(component_match_add) },
	{ 0x489a2089, __VMLINUX_SYMBOL_STR(drm_release) },
	{ 0xb8b5974, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xe6242986, __VMLINUX_SYMBOL_STR(perf_tp_event) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0x1ca8d45c, __VMLINUX_SYMBOL_STR(drm_dev_register) },
	{ 0x815588a6, __VMLINUX_SYMBOL_STR(clk_enable) },
	{ 0x46a8c4a8, __VMLINUX_SYMBOL_STR(of_find_i2c_adapter_by_node) },
	{ 0x3f4eb73c, __VMLINUX_SYMBOL_STR(drm_get_edid) },
	{ 0xca7c9bcb, __VMLINUX_SYMBOL_STR(drm_atomic_helper_update_plane) },
	{ 0xc6717328, __VMLINUX_SYMBOL_STR(drm_crtc_index) },
	{ 0x62a2b3d1, __VMLINUX_SYMBOL_STR(drm_atomic_helper_crtc_duplicate_state) },
	{ 0xf6ee1824, __VMLINUX_SYMBOL_STR(__pm_runtime_disable) },
	{ 0xfe411fe6, __VMLINUX_SYMBOL_STR(drm_calc_vbltimestamp_from_scanoutpos) },
	{ 0x3b92c1d, __VMLINUX_SYMBOL_STR(drm_framebuffer_reference) },
	{ 0xa30ae3a9, __VMLINUX_SYMBOL_STR(drm_dev_alloc) },
	{ 0x7ea764ce, __VMLINUX_SYMBOL_STR(component_unbind_all) },
	{ 0x7aa1756e, __VMLINUX_SYMBOL_STR(kvfree) },
	{ 0x8ea69e7, __VMLINUX_SYMBOL_STR(mipi_dsi_packet_format_is_long) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x6c09c2a4, __VMLINUX_SYMBOL_STR(del_timer) },
	{ 0x684bdf13, __VMLINUX_SYMBOL_STR(__pm_runtime_use_autosuspend) },
	{ 0xd10becd0, __VMLINUX_SYMBOL_STR(drm_gem_cma_create) },
	{ 0x8de13715, __VMLINUX_SYMBOL_STR(drm_format_vert_chroma_subsampling) },
	{ 0xa6e6d8ef, __VMLINUX_SYMBOL_STR(drm_mode_config_cleanup) },
	{ 0x3a1fba1a, __VMLINUX_SYMBOL_STR(component_add) },
	{ 0xf21e40e2, __VMLINUX_SYMBOL_STR(__pm_runtime_suspend) },
	{ 0x8f3bf70e, __VMLINUX_SYMBOL_STR(of_parse_phandle) },
	{ 0xc22ee8e3, __VMLINUX_SYMBOL_STR(drm_mode_config_reset) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0xd1647671, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_reset) },
	{ 0x1c792a04, __VMLINUX_SYMBOL_STR(arm_dma_ops) },
	{ 0xf19e9355, __VMLINUX_SYMBOL_STR(cpu_online_mask) },
	{ 0xcfec084e, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_mmap) },
	{ 0x5bfa0683, __VMLINUX_SYMBOL_STR(drm_atomic_helper_page_flip) },
	{ 0x30672332, __VMLINUX_SYMBOL_STR(drm_match_cea_mode) },
	{ 0xaedc4f0, __VMLINUX_SYMBOL_STR(drm_atomic_connectors_for_crtc) },
	{ 0x5cc509a4, __VMLINUX_SYMBOL_STR(nsecs_to_jiffies) },
	{ 0xb4137a45, __VMLINUX_SYMBOL_STR(drm_atomic_helper_swap_state) },
	{ 0xb6e6d99d, __VMLINUX_SYMBOL_STR(clk_disable) },
	{ 0x9331acd0, __VMLINUX_SYMBOL_STR(drm_cvt_mode) },
	{ 0xfe8a73ce, __VMLINUX_SYMBOL_STR(drm_crtc_handle_vblank) },
	{ 0xaf631f5f, __VMLINUX_SYMBOL_STR(gpio_to_desc) },
	{ 0x1afae5e7, __VMLINUX_SYMBOL_STR(down_interruptible) },
	{ 0xe9fdf1b3, __VMLINUX_SYMBOL_STR(drm_helper_probe_single_connector_modes) },
	{ 0x32653dd7, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x9885ffb1, __VMLINUX_SYMBOL_STR(mipi_dsi_host_unregister) },
	{ 0xe1311adb, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_off) },
	{ 0x4205ad24, __VMLINUX_SYMBOL_STR(cancel_work_sync) },
	{ 0xc87c1f84, __VMLINUX_SYMBOL_STR(ktime_get) },
	{ 0x45c784c2, __VMLINUX_SYMBOL_STR(platform_bus_type) },
	{ 0x555b2d71, __VMLINUX_SYMBOL_STR(component_bind_all) },
	{ 0xe2fae716, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0xb014a43b, __VMLINUX_SYMBOL_STR(drm_fbdev_cma_init) },
	{ 0x91166714, __VMLINUX_SYMBOL_STR(devm_ioremap_resource) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0xb85cb07d, __VMLINUX_SYMBOL_STR(debugfs_print_regs32) },
	{ 0x36fdda67, __VMLINUX_SYMBOL_STR(hdmi_infoframe_pack) },
	{ 0x9580deb, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x28cc25db, __VMLINUX_SYMBOL_STR(arm_copy_from_user) },
	{ 0x85d23016, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x223375dd, __VMLINUX_SYMBOL_STR(drm_vblank_no_hw_counter) },
	{ 0xa24c8064, __VMLINUX_SYMBOL_STR(__pm_runtime_resume) },
	{ 0x4e0604e4, __VMLINUX_SYMBOL_STR(trace_event_buffer_reserve) },
	{ 0x5500c89, __VMLINUX_SYMBOL_STR(drm_dev_unref) },
	{ 0x816366e1, __VMLINUX_SYMBOL_STR(drm_vblank_init) },
	{ 0x6c38efb0, __VMLINUX_SYMBOL_STR(component_master_del) },
	{ 0xca45efbc, __VMLINUX_SYMBOL_STR(drm_format_horz_chroma_subsampling) },
	{ 0x9b5bd860, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0x78f4e3c9, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_get_sg_table) },
	{ 0x556e4390, __VMLINUX_SYMBOL_STR(clk_get_rate) },
	{ 0x30f4621d, __VMLINUX_SYMBOL_STR(drm_atomic_helper_crtc_reset) },
	{ 0xb6656584, __VMLINUX_SYMBOL_STR(drm_universal_plane_init) },
	{ 0x348e8271, __VMLINUX_SYMBOL_STR(__platform_driver_register) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0xbcccd83e, __VMLINUX_SYMBOL_STR(drm_gem_cma_vm_ops) },
	{ 0x42df7f10, __VMLINUX_SYMBOL_STR(drm_connector_cleanup) },
	{ 0xf4fa543b, __VMLINUX_SYMBOL_STR(arm_copy_to_user) },
	{ 0x7e1b445f, __VMLINUX_SYMBOL_STR(__drm_atomic_helper_plane_duplicate_state) },
	{ 0xd871ec5, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_duplicate_state) },
	{ 0xc268d475, __VMLINUX_SYMBOL_STR(__drm_atomic_helper_crtc_duplicate_state) },
	{ 0x275ef902, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x810b5de3, __VMLINUX_SYMBOL_STR(drm_atomic_helper_set_config) },
	{ 0xe707d823, __VMLINUX_SYMBOL_STR(__aeabi_uidiv) },
	{ 0x88ab6fe3, __VMLINUX_SYMBOL_STR(kgdb_active) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0xa2d09977, __VMLINUX_SYMBOL_STR(trace_define_field) },
	{ 0x1a546ddd, __VMLINUX_SYMBOL_STR(drm_mm_init) },
	{ 0x57ecc0c4, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0x568d47f, __VMLINUX_SYMBOL_STR(drm_irq_install) },
	{ 0x48ba1b3a, __VMLINUX_SYMBOL_STR(of_clk_src_onecell_get) },
	{ 0x33fe520c, __VMLINUX_SYMBOL_STR(devm_clk_register) },
	{ 0x429be6d3, __VMLINUX_SYMBOL_STR(remove_conflicting_framebuffers) },
	{ 0xcc2ce6c2, __VMLINUX_SYMBOL_STR(drm_dev_unregister) },
	{ 0x59c5ec88, __VMLINUX_SYMBOL_STR(drm_plane_index) },
	{ 0xcc337fd5, __VMLINUX_SYMBOL_STR(drm_fbdev_cma_restore_mode) },
	{ 0xbd7da979, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x51d559d1, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xe9bff861, __VMLINUX_SYMBOL_STR(down_trylock) },
	{ 0x4d50c1e2, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_put) },
	{ 0x45f768a8, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xe95ab712, __VMLINUX_SYMBOL_STR(drm_atomic_helper_prepare_planes) },
	{ 0x240ab166, __VMLINUX_SYMBOL_STR(drm_crtc_init_with_planes) },
	{ 0xb3e39a0b, __VMLINUX_SYMBOL_STR(drm_put_dev) },
	{ 0x6271f369, __VMLINUX_SYMBOL_STR(of_graph_get_next_endpoint) },
	{ 0x911a619d, __VMLINUX_SYMBOL_STR(drm_atomic_helper_plane_reset) },
	{ 0x80c16e6f, __VMLINUX_SYMBOL_STR(of_find_property) },
	{ 0xfc082392, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0x1f94d0b4, __VMLINUX_SYMBOL_STR(drm_gem_dumb_destroy) },
	{ 0xfc72a2e0, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_on) },
	{ 0x447f9d6d, __VMLINUX_SYMBOL_STR(drm_atomic_state_free) },
	{ 0xe95d592c, __VMLINUX_SYMBOL_STR(dma_sync_wait) },
	{ 0x60c0233c, __VMLINUX_SYMBOL_STR(drm_fb_cma_get_gem_obj) },
	{ 0x3feaf038, __VMLINUX_SYMBOL_STR(trace_event_reg) },
	{ 0xe29e752c, __VMLINUX_SYMBOL_STR(drm_panel_attach) },
	{ 0xb2c912af, __VMLINUX_SYMBOL_STR(drm_fbdev_cma_hotplug_event) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x3934a77b, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xadb6934c, __VMLINUX_SYMBOL_STR(drm_probe_ddc) },
	{ 0x72f2ba0, __VMLINUX_SYMBOL_STR(drm_fb_cma_create) },
	{ 0x3ecfd409, __VMLINUX_SYMBOL_STR(drm_framebuffer_unreference) },
	{ 0xae9d90ab, __VMLINUX_SYMBOL_STR(platform_get_resource) },
	{ 0x30574af0, __VMLINUX_SYMBOL_STR(drm_read) },
	{ 0x67633846, __VMLINUX_SYMBOL_STR(drm_mm_insert_node_generic) },
	{ 0xf6944d79, __VMLINUX_SYMBOL_STR(noop_llseek) },
	{ 0x16e5c2a, __VMLINUX_SYMBOL_STR(mod_timer) },
	{ 0x49d87b7f, __VMLINUX_SYMBOL_STR(drm_add_edid_modes) },
	{ 0x1cc29e89, __VMLINUX_SYMBOL_STR(of_clk_add_provider) },
	{ 0x8e865d3c, __VMLINUX_SYMBOL_STR(arm_delay_ops) },
	{ 0x737aba32, __VMLINUX_SYMBOL_STR(bus_find_device) },
	{ 0xcb9dbc91, __VMLINUX_SYMBOL_STR(drm_atomic_set_fb_for_plane) },
	{ 0xf4e97b1a, __VMLINUX_SYMBOL_STR(rpi_firmware_property) },
	{ 0xd1145951, __VMLINUX_SYMBOL_STR(drm_debugfs_create_files) },
	{ 0x1dd71f7a, __VMLINUX_SYMBOL_STR(drm_err) },
	{ 0xce74ac74, __VMLINUX_SYMBOL_STR(drm_connector_init) },
	{ 0x13ca3b16, __VMLINUX_SYMBOL_STR(of_match_device) },
	{ 0x6cfdda1, __VMLINUX_SYMBOL_STR(drm_mode_connector_update_edid_property) },
	{ 0xcdb5fd83, __VMLINUX_SYMBOL_STR(dma_alloc_from_coherent) },
	{ 0x1bdea3e7, __VMLINUX_SYMBOL_STR(drm_gem_vm_close) },
	{ 0x20645642, __VMLINUX_SYMBOL_STR(drm_debug) },
	{ 0x4ea1f5a2, __VMLINUX_SYMBOL_STR(drm_gem_object_free) },
	{ 0xe3d0b10c, __VMLINUX_SYMBOL_STR(drm_gem_prime_fd_to_handle) },
	{ 0xabdcd617, __VMLINUX_SYMBOL_STR(of_get_address) },
	{ 0xe8a1062d, __VMLINUX_SYMBOL_STR(drm_plane_helper_disable) },
	{ 0xda6214cc, __VMLINUX_SYMBOL_STR(gpiod_get_raw_value_cansleep) },
	{ 0x23f58fa1, __VMLINUX_SYMBOL_STR(drm_plane_cleanup) },
	{ 0x729a7350, __VMLINUX_SYMBOL_STR(drm_ioctl) },
	{ 0x36c2df15, __VMLINUX_SYMBOL_STR(drm_gem_prime_import) },
	{ 0x27683889, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0x25098fea, __VMLINUX_SYMBOL_STR(drm_gem_mmap) },
	{ 0x7840e6fa, __VMLINUX_SYMBOL_STR(drm_atomic_helper_plane_duplicate_state) },
	{ 0xb5684e29, __VMLINUX_SYMBOL_STR(idr_find_slowpath) },
	{ 0x2030d5ad, __VMLINUX_SYMBOL_STR(drm_atomic_helper_wait_for_vblanks) },
	{ 0x7ee310ef, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_destroy_state) },
	{ 0x950c6b86, __VMLINUX_SYMBOL_STR(__drm_atomic_helper_plane_destroy_state) },
	{ 0x4f5de93c, __VMLINUX_SYMBOL_STR(pm_runtime_enable) },
	{ 0x6a9bdead, __VMLINUX_SYMBOL_STR(trace_event_ignore_this_pid) },
	{ 0xd27949d, __VMLINUX_SYMBOL_STR(drm_atomic_helper_check) },
	{ 0xa3291d10, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0x782737c6, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_vunmap) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x5c8dadcd, __VMLINUX_SYMBOL_STR(drm_irq_uninstall) },
	{ 0x38a4f7ae, __VMLINUX_SYMBOL_STR(drm_format_num_planes) },
	{ 0x7c9a7371, __VMLINUX_SYMBOL_STR(clk_prepare) },
	{ 0x26a7a854, __VMLINUX_SYMBOL_STR(drm_atomic_helper_commit_modeset_disables) },
	{ 0x4a34edc6, __VMLINUX_SYMBOL_STR(drm_crtc_send_vblank_event) },
	{ 0x50fad434, __VMLINUX_SYMBOL_STR(round_jiffies_up) },
	{ 0xb24849fe, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0x7de0183e, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_get) },
	{ 0x3d627d29, __VMLINUX_SYMBOL_STR(of_get_named_gpio_flags) },
	{ 0xce225efb, __VMLINUX_SYMBOL_STR(trace_event_buffer_commit) },
	{ 0x7f24de73, __VMLINUX_SYMBOL_STR(jiffies_to_usecs) },
	{ 0x3b9d009a, __VMLINUX_SYMBOL_STR(drm_format_plane_cpp) },
	{ 0x4724a051, __VMLINUX_SYMBOL_STR(__dma_request_channel) },
	{ 0x1887364e, __VMLINUX_SYMBOL_STR(devm_clk_get) },
	{ 0xfd1fdf8e, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x1a770ac3, __VMLINUX_SYMBOL_STR(drm_detect_hdmi_monitor) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x598542b2, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x3ec67174, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_dpms) },
	{ 0xd0678c89, __VMLINUX_SYMBOL_STR(drm_gem_prime_handle_to_fd) },
	{ 0xf7577055, __VMLINUX_SYMBOL_STR(rpi_firmware_get) },
	{ 0x76d9b876, __VMLINUX_SYMBOL_STR(clk_set_rate) },
	{ 0x8c834607, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_import_sg_table) },
	{ 0xd85cd67e, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0xd087f2e1, __VMLINUX_SYMBOL_STR(event_triggers_call) },
	{ 0x5b8b7228, __VMLINUX_SYMBOL_STR(drm_connector_unregister) },
	{ 0x47f138e6, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0x5fc72fca, __VMLINUX_SYMBOL_STR(drm_dev_set_unique) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x9e605bd5, __VMLINUX_SYMBOL_STR(of_graph_get_remote_port_parent) },
	{ 0x62d7cbb1, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0xa717c1b2, __VMLINUX_SYMBOL_STR(drm_atomic_helper_commit_planes) },
	{ 0x28d6861d, __VMLINUX_SYMBOL_STR(__vmalloc) },
	{ 0xed79ff3c, __VMLINUX_SYMBOL_STR(drm_atomic_helper_crtc_destroy_state) },
	{ 0x62f92f03, __VMLINUX_SYMBOL_STR(drm_mode_config_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xd363075e, __VMLINUX_SYMBOL_STR(drm_helper_hpd_irq_event) },
	{ 0xcc48240b, __VMLINUX_SYMBOL_STR(drm_hdmi_avi_infoframe_from_display_mode) },
	{ 0x5c6df4a5, __VMLINUX_SYMBOL_STR(component_del) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xe9103183, __VMLINUX_SYMBOL_STR(trace_event_raw_init) },
	{ 0x499cb58c, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0x1ff6c8b8, __VMLINUX_SYMBOL_STR(perf_trace_buf_prepare) },
	{ 0x6b79d3f0, __VMLINUX_SYMBOL_STR(drm_panel_detach) },
	{ 0x4be7fb63, __VMLINUX_SYMBOL_STR(up) },
	{ 0xb79ec15d, __VMLINUX_SYMBOL_STR(mipi_dsi_create_packet) },
	{ 0x3559594b, __VMLINUX_SYMBOL_STR(drm_atomic_helper_cleanup_planes) },
	{ 0x1db7dc40, __VMLINUX_SYMBOL_STR(pgprot_kernel) },
	{ 0x7794e816, __VMLINUX_SYMBOL_STR(drm_debugfs_remove_files) },
	{ 0xdd150721, __VMLINUX_SYMBOL_STR(drm_mm_takedown) },
	{ 0x1cfb04fa, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x670e27f6, __VMLINUX_SYMBOL_STR(dma_common_mmap) },
	{ 0x48711182, __VMLINUX_SYMBOL_STR(pm_runtime_set_autosuspend_delay) },
	{ 0x1bf56330, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0xff3239d4, __VMLINUX_SYMBOL_STR(drm_atomic_helper_disable_plane) },
	{ 0xbbb73492, __VMLINUX_SYMBOL_STR(trace_raw_output_prep) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0x8083c7ed, __VMLINUX_SYMBOL_STR(drm_mode_probed_add) },
	{ 0x4d6576c4, __VMLINUX_SYMBOL_STR(component_master_add_with_match) },
	{ 0xb2d48a2e, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0xd4669fad, __VMLINUX_SYMBOL_STR(complete) },
	{ 0x1148b623, __VMLINUX_SYMBOL_STR(drm_fbdev_cma_fini) },
	{ 0xf147dcb2, __VMLINUX_SYMBOL_STR(hdmi_spd_infoframe_init) },
	{ 0x6e532d2f, __VMLINUX_SYMBOL_STR(platform_get_irq) },
	{ 0x3c93ea25, __VMLINUX_SYMBOL_STR(trace_seq_printf) },
	{ 0x3f31574c, __VMLINUX_SYMBOL_STR(of_drm_find_panel) },
	{ 0x4d0d5ab0, __VMLINUX_SYMBOL_STR(platform_driver_unregister) },
	{ 0xa4466414, __VMLINUX_SYMBOL_STR(drm_mm_remove_node) },
	{ 0xc360e7e2, __VMLINUX_SYMBOL_STR(drm_ut_debug_printk) },
	{ 0xf76034d9, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_init) },
	{ 0xab70a733, __VMLINUX_SYMBOL_STR(drm_gem_cma_free_object) },
	{ 0x5bfab1ad, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_vmap) },
	{ 0x4587c37a, __VMLINUX_SYMBOL_STR(of_node_put) },
	{ 0xe582a165, __VMLINUX_SYMBOL_STR(devm_kmalloc) },
	{ 0x7cf9099, __VMLINUX_SYMBOL_STR(wait_for_completion_timeout) },
	{ 0x50cc9353, __VMLINUX_SYMBOL_STR(drm_connector_register) },
	{ 0xee4faa30, __VMLINUX_SYMBOL_STR(devm_request_threaded_irq) },
	{ 0xbc5146bd, __VMLINUX_SYMBOL_STR(drm_atomic_helper_commit_modeset_enables) },
	{ 0x28cd26f8, __VMLINUX_SYMBOL_STR(drm_mode_crtc_set_gamma_size) },
	{ 0x725a6962, __VMLINUX_SYMBOL_STR(mipi_dsi_host_register) },
	{ 0x82e4efca, __VMLINUX_SYMBOL_STR(drm_poll) },
	{ 0xc569d8ce, __VMLINUX_SYMBOL_STR(__clk_get_name) },
	{ 0xbc5ccf21, __VMLINUX_SYMBOL_STR(drm_gem_cma_dumb_map_offset) },
	{ 0xb859f38b, __VMLINUX_SYMBOL_STR(krealloc) },
	{ 0x2e7a4300, __VMLINUX_SYMBOL_STR(drm_rgb_quant_range_selectable) },
	{ 0xa0ffc40e, __VMLINUX_SYMBOL_STR(drm_open) },
	{ 0x45399e05, __VMLINUX_SYMBOL_STR(drm_atomic_helper_plane_destroy_state) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=drm,drm_kms_helper,drm_mipi_dsi";

MODULE_ALIAS("of:N*T*Cbrcm,bcm2835-vc4*");

MODULE_INFO(srcversion, "032BDFAB08C576AA5D93C08");
